# Site settings
title: Open Bioinformatics Foundation GSoC
email: gsoc@mailman.open-bio.org
description: > # this means to ignore newlines until "baseurl:"
    The Open Bioinformatics Foundation (OBF) is a non-profit, volunteer-run
    group dedicated to promoting the practice and philosophy of Open Source software
    development and Open Science within the biological research community. On this
    page, the OBF coordinates its GSoC participation.
baseurl: "GSoC" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: OBF_news
theme: minima

include: ['_historic']

# Build settings
markdown: kramdown

kramdown:
    auto_ids:   true
    toc_levels: 2..3
sass:
    sass_dir: assets
